version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"
  jobs:
    post_create_environment:
      # Install poetry
      - python -m pip install uv
    post_install:
      # Install dependencies
      - "VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras --editable --active"

sphinx:
  configuration: docs/source/conf.py
