version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      # Install poetry
      - python -m pip install poetry
    post_install:
      # Install dependencies with 'docs' dependency group
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

sphinx:
  configuration: docs/source/conf.py
